export const diseases = [
  "Gynecomastia",
  "Lipoma",
  "Lasik ",
  "Cataract",
  "Vericose veins",
  "Piles",
  "Fissure",
  "Fistula",
  "Gallstone",
  "Circumcision",
  "Cyst",
  "Kidney stone",
  "Knee replacement",
  "Liposuction",
];
