export const diseasesList = [
  "Pilonidal Sinus",
  "Piles",
  "Rectal Prolapse",
  "Fissure",
  "Fistula",
  "Fecal Incontinence",
  "Constipation",
  "Hemorrhoids",
  "Umbilical Hernia",
  "Hydrocele",
  "Inguinal Hernia",
  "Incisional Hernia",
  "Appendicitis",
  "Gallstone",
  "Hernia",
  "Achalasia Cardia",
  "Acid Reflux Surgery",
  "Large Intestine",
  "Indirect Hernia",
  "Small Intestine",
  "Colonoscopy",
  "Gastric Bypass Surgery",
  "Pain During Intercourse",
  "Vaginoplasty",
  "Labiaplasty",
  "Vaginal Discharge",
  "Laser Vaginal Tightening",
  "Vaginal Dryness",
  "Ovarian Cyst",
  "Hysterectomy",
  "Hymenoplasty",
  "Clitoral Hoodoplasty",
  "Abortion",
  "Hysteroscopy",
  "Pap Smear",
  "Vaginal Rejuvenation",
  "Ectopic Pregnancy",
  "Laser Vaginal Rejuvenation",
  "Vaginal Recurrent Infection",
  "Pelvic Pain",
  "Female Urinary Problems",
  "Lichen Sclerosus",
  "Menstrual Disorders",
  "Preconception Care",
  "Uterine Fibroid",
  "Pcos Pcod",
  "Pregnancy Care",
  "Medical Termination Of Pregnancy",
  "Laser Vaginal Bleaching",
  "Anal Bleaching",
  "Vaginal Wart",
  "Molar Pregnancy",
  "Bartholin Cyst",
  "Miscarriage",
  "Endometriosis",
  "Adenomyosis",
  "Myomectomy",
  "Dilation And Evacuation (D&amp;E)",
  "Polypectomy",
  "Turbinate Reduction",
  "Uvulopalatopharyngoplasty",
  "Adenoidectomy",
  "Myringotomy",
  "Microlaryngeal",
  "Mastoidectomy",
  "Tongue Base Reduction",
  "Tonsils Removal",
  "Deviated Nasal Septum",
  "Eardrum Surgery",
  "Sinus Surgery",
  "Thyroidectomy",
  "Tonsillectomy",
  "Ear Surgery",
  "Sinusitis",
  "Tympanoplasty",
  "Fess Surgery",
  "Stapedectomy",
  "Septoplasty",
  "Tonsillitis",
  "Adenoids",
  "Hearing Problem",
  "Thyroid Infection",
  "Chronic Sinusitis",
  "Recurrent Sinusitis",
  "Subacute Sinusitis",
  "Mastoiditis",
  "Parotidectomy",
  "Nose Surgery",
  "Vocal Cord Polyps",
  "Adenotonsillectomy",
  "Otitis Media",
  "Nasal Polyps",
  "Turbinoplasty",
  "Ear Infection",
  "Ear Hole",
  "Throat Infection",
  "Middle Ear Perforation",
  "Urinary Tract Infection",
  "Urinary Incontinence",
  "Erectile Dysfunction",
  "Stress Urinary Incontinence",
  "Circumcision",
  "Kidney Stones",
  "Male Urinary Tract Infection",
  "Prostate Enlargement",
  "Phimosis",
  "Paraphimosis",
  "Foreskin Infection",
  "Balanoposthitis",
  "Balanitis",
  "Frenuloplasty",
  "Cystoscopy",
  "Cystolithotripsy",
  "DJ Stent",
  "cystolithotomy",
  "Urethral Stricture",
  "pyeloplasty",
  "nephrostomy",
  "Corn Removal",
  "Vasectomy",
  "Toenail treatment",
  "Testicular Torsion",
  "Epididymal Cyst",
  "Varicose Veins",
  "Varicocele",
  "Diabetic Foot Ulcer",
  "AV Fistula For Dialysis",
  "Deep Vein Thrombosis",
  "Spider Veins",
  "Gynecomastia",
  "Liposuction",
  "Lipoma",
  "Hair Transplant",
  "Sebaceous Cyst",
  "Breast Lift",
  "Rhinoplasty",
  "Breast Reduction",
  "Breast Augmentation",
  "Breast Lump",
  "Hair Loss",
  "Breast Surgery",
  "Axillary Breast",
  "Scar Removal",
  "Abdominoplasty",
  "Double Chin",
  "Buccal Fat",
  "Earlobe Repair",
  "Blepharoplasty",
  "Hairfall PRP",
  "Carpal Tunnel Syndrome",
  "Knee Replacement",
  "Spine Surgery",
  "Hip Replacement",
  "Arthroscopy",
  "ACL Tear",
  "Rotator Cuff Repair",
  "Bankart Surgery",
  "Bankart Repair",
  "Meniscus Repair Surgery",
  "Shoulder Replacement Surgery",
  "Discectomy",
  "Laminectomy",
  "Acdf Surgery",
  "Spinal Fusion",
  "Ligament Injury",
  "Knee Arthroscopy",
  "Shoulder Arthroscopy",
  "Lasik",
  "Cataract",
  "Squint Surgery",
  "Glaucoma Surgery",
  "Retinal Detachment Surgery",
  "Diabetic Retinopathy Treatment",
  "Intravitreal Injections",
  "Vitrectomy",
  "Monofocal Lens",
  "Multifocal Lens",
  "Toric Lens",
  "PRK Lasik",
  "Smile Lasik Surgery",
  "Femto Lasik Surgery",
  "ICL Surgery",
  "Macular Edema",
  "Retinal Surgery",
  "Contoura Vision",
  "Phaco Surgery",
  "Pterygium",
  "Male Infertility",
  "Female Infertility",
  "Ivf",
  "Iui",
  "Embryo Transfer",
  "ICSI Treatment",
  "Teeth Alignment (Fix)",
  "Dental Others",
  "Crossbite Teeth",
  "Overbite Teeth",
  "Openbite Teeth",
  "Bariatric Surgery",
  "Intragastric Balloon",
  "Face Threadlift",
  "Botox",
  "Derma Fillers",
  "Vampire Facial with Dermaroller",
];
